# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blockchain & Decentralized Systems Aachen
author: Michael A. Heuer
email: decentralised.systems@gmail.com
description: Website of the Aachen-based Meetup group.
baseurl: ''
url: 'https://decentralized-systems.github.io'
#twitter_username: Michael_A_Heuer
#github_username: Michael-A-Heuer
markdown: kramdown
google_analytics: UA-123745916-1

# If you want to link only specific pages in your header,
# add the path to the pages in order as they should show up
header_pages:
  - first-steps.md
  - meetup.md
  - about.md

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%B %-d, %Y" 
